- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#3 
- SSE 알림 구독 및 전송 기능 1차적으로 구현
- 이하 내용 추가 작업 필요
- 1. User Entity 완성 후 서비스 저장 로직 변경
- 2. SSE 연결 관리 기능 추가
- 3. emitter를 활용한 알림 조회 및 상태 변경 로직 추가
> feat: SSE 알림 구독 및 전송 기능 1차 구현(#3, SCRUM-201)

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#3 
SSE Subscribe 구현을 위해 공동 작업 완료.
> refactor: SSE subscribe 구현(#3, SCRUM-201)

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
> fix: sse subscribe return 값 오류 해결(#3, SCRUM-201)

- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
> fix: emitter userId에서 username으로 매칭되도록 수정(#3, SCRUM-201)

- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
- src/main/java/kr/ssok/ssom/backend/global/client/LlmServiceClient.java
- src/main/java/kr/ssok/ssom/backend/global/dto/LlmApiRequestDto.java
- src/main/java/kr/ssok/ssom/backend/global/dto/LlmApiResponseDto.java
- src/main/java/kr/ssok/ssom/backend/global/dto/LlmIssueRequestDto.java
- src/main/java/kr/ssok/ssom/backend/global/dto/LlmIssueResponseDto.java
- src/main/java/kr/ssok/ssom/backend/global/dto/LogRequestDto.java
- src/main/java/kr/ssok/ssom/backend/global/dto/LogSummaryMessageDto.java
> fix: openfeign 관련 코드 수정(#10, SCRUM-215)

- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/dto/LogDto.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/dto/LogInfoResponseDto.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/entity/LogSummary.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/repository/LogSummaryRepository.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
- src/main/java/kr/ssok/ssom/backend/global/dto/LogSummaryResponseDto.java
close #10 
- 로그 AI 요약 관련 api 작성
> feat: 로그 LLM 관련 api

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertOpensearchDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertOpensearchRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/entity/AlertStatus.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#27 
1. opensearch 로 부터 String 데이터를 받아 JSON 포맷으로 parsing
2. 알림 객체로 저장
3. SSE 알림 전송
> feat: opensearch SSE 알림 연동 (#27, SCRUM-205)

- build.gradle
- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/dto/LogDataDto.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/dto/LogDto.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/dto/ServiceDto.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/entity/LogSummary.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
- src/main/java/kr/ssok/ssom/backend/global/config/OpenSearchConfig.java
- opensearch client 의존성 및 config 추가
- logging service에서 서비스 목록 조회, 로그 목록 조회, id를 통한 로그 조회 기능 작성
- DB 방식을 이용한 불필요한 코드 삭제
- DTO에 수정 있음 (LogDataDto 등, 주의 필요)
> feat: opensearch 로그 관련 api

- src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/global/dto/GitHubWebhookSenderDto.java
#20 
Log 조회 방식 변경 후 Dto 매칭 수정
및 CI/CD 테스트
> fix : issue dto 매칭 및 ci/cd 테스트

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#6 
알림 개별 건에 대해 삭제 처리.
(DB 에서 완전 삭제)
> feat: 알림 개별 삭제 기능 구현 (#6, SCRUM-209)

- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/entity/Alert.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#30 
grafana 알림 기능 구현(SSE) 및 Alert에 발생 시간 필드 추가
> feat: grafana 알림 기능 구현 및 Alert에 발생 시간 필드 추가 (#30, SCRUM-206)

- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
- 로그 목록 조회 api에 레벨별, 서비스별 필터링 기능 추가
> feat: 로그 목록 필터링 기능 추가

- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
> feat: 로그 목록 조회 시 최신순으로 정렬

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/fcm/FcmController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertIssueRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertOpensearchRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertSendRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/fcm/FcmRegisterRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/entity/Alert.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/global/client/FirebaseClient.java
- src/main/java/kr/ssok/ssom/backend/global/config/FirebaseConfig.java
- src/main/java/kr/ssok/ssom/backend/global/dto/FcmMessageRequestDto.java
#19 
- FCM 기능 구현
- 추 후 Exception 처리 수정 필요.
> feat : FCM 기능 구현 (#19, SCRUM-212)

- src/main/java/kr/ssok/ssom/backend/global/config/OpenSearchConfig.java
#20 
refactor : OpenSearchConfig 하드코딩 된 부분 Config 값 사용하도록 수정
> refactor : OpenSearchConfig 하드코딩 된 부분 Config 값 사용하도록 수정

- src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
#20 
feat : llm issue 초안 작성 debugging용 log.info
> feat : llm issue 초안 작성 debugging용 log.info

- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
- 새 LLM 요약 생성 api의 URL 변경
- /{logID} 제거
> fix: 새 LLM 요약 생성 api의 URL 변경

- src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
#20 
feat : llm issue 초안 작성 debugging용 log.info / 예외조건 수정
> feat : llm issue 초안 작성 debugging용 log.info / 예외조건 수정

- src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/global/dto/LlmApiResponseDto.java
#20 
feat : llm issue 초안 작성 response dto boolean -> Boolean
> feat : llm issue 초안 작성 response dto boolean -> Boolean

- src/main/java/kr/ssok/ssom/backend/global/dto/LogSummaryResponseDto.java
- LLM 측 응답에서 로그 부분이 사라짐에 따라 dto 변경
> fix: LLM response dto 수정

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#19 
- 부서 권한 부여 시 String 비교하는 함수 contains 로 변경 
- 소문자/대문자 모두 비교 가능하도록 변경
> feat: 부서 권한 비굣값 contains 로 수정(#19, SCRUM-212)

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#19 
- devops url (send (X) -> devops (O))
> fix: devops endpoint url 변경(#19, SCRUM-212)

- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
- src/main/java/kr/ssok/ssom/backend/global/exception/BaseResponseStatus.java
- Logging 서비스에 예외 처리 추가
- SSE 관련 기능 제외
> chore: Logging 서비스 예외 처리 추가

- src/main/java/kr/ssok/ssom/backend/domain/logging/entity/LogSummary.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/repository/LogSummaryRepository.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
- 기존 LLM 요약 조회 기능 로직 수정
- DB 조회 시 로그 ID 대신 로그 메시지를 사용하도록 수정
> fix: 기존 LLM 요약 조회 시 로그 메시지 기준 사용

- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertIssueRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertModifyRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertOpensearchRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
> fix: deserialize 해결(#30, SCRUM-206)

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#22 
- devops에서 받은 데이터 확인을 위한 로그 수정
> chore: devops 알림 생성 디버깅을 위한 로그 수정(#22, SCRUM-207)

- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/sse/EmitterWithFilter.java
> feat: 실시간 로그 SSE 기능

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
- src/main/java/kr/ssok/ssom/backend/domain/user/repository/UserRepository.java
- src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
- src/main/java/kr/ssok/ssom/backend/global/exception/BaseResponseStatus.java
#20 
whiteList로 허용된 부분에 비동기 Security 컨텍스트를 전파하려고해서 UserPrincipal이 null로 오던 문제 해결
> feat : sse 관련 controller 인증 설정 충돌 해결

- src/main/java/kr/ssok/ssom/backend/SsomBackendApplication.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/exception/SseExceptionHandler.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/scheduler/SseConnectionMonitor.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
- src/main/java/kr/ssok/ssom/backend/global/config/WebMvcConfig.java
#20 
MODE_INHERITABLETHREADLOCAL은 직접 생성한 자식 스레드에만 전파
SSE 콜백은 Servlet 컨테이너 스레드에서 실행되어 Security Context 없음 응답 커밋 후 예외 처리 시도로 인한 "Response already committed" 오류
- SecurityConfig 개선
- SSE 전용 Exception Handler 생성
- AlertServiceImpl 핵심 개선
- AlertController 강화
- WebMvcConfig 비동기 처리 최적화
- SSE 연결 모니터링 시스템 구축
- 애플리케이션 설정 업데이트
> feat : SSE의 비동기 콜백 문제로 Spring Security Context 비전파 문제 해결

- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#34 
알림 상태 변경 처리 시 디버깅을 위한 로그를 추가합니다.
> test: 알림 상태 변경 디버깅 로그 추가

- src/main/java/kr/ssok/ssom/backend/domain/user/controller/BiometricController.java
- src/main/java/kr/ssok/ssom/backend/domain/user/dto/BiometricLoginRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/user/dto/BiometricRegistrationRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/user/service/BiometricFailureService.java
- src/main/java/kr/ssok/ssom/backend/domain/user/service/BiometricService.java
- src/main/java/kr/ssok/ssom/backend/domain/user/service/Impl/UserServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/global/exception/BaseResponseStatus.java
#98 
- VOICE 생체인증 타입 제거 (FINGERPRINT, FACE만)
- 3회 실패 시 디바이스 차단 기능 강화 및 Redis 기반 차단 관리
- 일반 로그인 성공 시 모든 디바이스 차단 자동 해제 기능 추가
- Repository 전용 업데이트 메서드 사용으로 DB 성능 최적화
- BiometricController 권한 체크 추가 (본인만 조회/해제 가능)
- BaseResponseStatus에 BIOMETRIC_DEVICE_BLOCKED, FORBIDDEN 추가
- 생체인증 실패 처리 로직 개선 (차단 → 일반로그인 → 해제 플로우)
> feat: 생체인증 시스템 보안 및 성능 개선

- src/main/java/kr/ssok/ssom/backend/domain/user/controller/BiometricController.java
#98 
- employeeId 를 파라미터로 받지 않고 userPrincipal 사용
> fix : 생체인증 상태 확인 본인확인 수정

- src/main/java/kr/ssok/ssom/backend/global/controller/HealthController.java
#18 
health check controller 정상 작동 및 오류 해결 확인 후 debugging log 제거
> hotfix : EKS health check

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/fcm/FcmController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmServiceImpl.java
#6 
-fcm UserPrincipal 쓰는 걸로 변경
-alertService Transactional 사용하는 위치 수정
> fix: fcm UserPrincipal 및 alertService Transaction 수정 (#6, SCRUM-209)

- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#6 
#27 
알림에 빈 값 온 경우 return 처리 (에러X)
> feat: opensearch 알림 리스트 빈 경우 return 처리

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/fcm/FcmController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmServiceImpl.java
> feat: fcm 디버깅 로그 추가

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/fcm/FcmController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/fcm/FcmServiceImpl.java
> merge main <- develop

- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/fcm/FcmRegisterRequestDto.java
> fix: 토큰 필드명 변경

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/fcm/FcmController.java
> fix: 필드명 일치

- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
> null 처리 수정

- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
> fix: 로그 SSE 이벤트명 변경

- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
> 로그 SSE 이벤트명 변경

- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/entity/Alert.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertStatusRepository.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
#6 
알림 실제 발생 시간 최신 순으로 정렬하여 전송
> feat: 알림 알림 실제 발생 시간 최신 순으로 정렬하여 전송 (#6, SCRUM-209)

- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
> fix: data type 오류 해결(#6, SCRUM-209)

- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertResponseDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/entity/Alert.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
> fix: datatype String 으로 원복(#6, SCRUM-209)

- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
> fix: repository save 누락 오류 해결

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertIssueRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/issue/service/IssueService.java
#31 
이슈 알림이 처리된 후 이슈DB 상태 업데이트
> feat: 이슈 알림 생성 후 Issue status 변경 처리(#31, SCRUM-208)

- src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
> test: 디버깅 로그 추가(#31, SCRUM-208)

- src/main/java/kr/ssok/ssom/backend/domain/issue/service/Impl/IssueServiceImpl.java
#31 
- issue close 시 status 변경이 되지 않아 transactional(readOnly=true) 제거
> fix: issue service 에서 transactional 제거 (#31, SCRUM-208)

- src/main/java/kr/ssok/ssom/backend/domain/logging/controller/LoggingController.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/dto/LogsScrollResponseDto.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/logging/service/LoggingService.java
> feat: 무한스크롤 방식의 로그 조회 기능 추가

- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
> fix: 무한스크롤 방식의 로그 조회 기능 수정

- build.gradle
- docker/kafka/docker-compose.kafka.yml
- docs/kafka/README-KAFKA-SETUP.md
- docs/kafka/README-TOPIC-BUILDER.md
- scripts/kafka/create-topics.sh
- scripts/kafka/monitor-topics.sh
- scripts/kafka/setup-permissions.sh
- scripts/kafka/start-kafka.sh
- scripts/kafka/stop-kafka.sh
- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/kafka/AlertCreatedEvent.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/kafka/UserAlertEvent.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertRepository.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertStatusRepository.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaConsumer.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaProducer.java
- src/main/java/kr/ssok/ssom/backend/global/config/KafkaConfig.java
- src/test/java/kr/ssok/ssom/backend/domain/alert/performance/AlertLoadTest.java
- src/test/java/kr/ssok/ssom/backend/domain/alert/performance/AlertPerformanceTest.java
- src/test/java/kr/ssok/ssom/backend/domain/alert/performance/BasicPerformanceTest.java
- src/test/java/kr/ssok/ssom/backend/domain/alert/performance/PerformanceTestRunner.java
- src/test/java/kr/ssok/ssom/backend/domain/alert/performance/SimpleAlertPerformanceTest.java
- src/test/java/kr/ssok/ssom/backend/domain/user/dto/LoginResponseDtoTest.java
- src/test/java/kr/ssok/ssom/backend/domain/user/dto/UserDtoTestSuite.java
- src/test/java/kr/ssok/ssom/backend/global/config/KafkaConfigTest.java
#165 
feat: Kafka 기반 비동기 Alert 처리 인프라 구성
- Kafka Producer/Consumer 구성을 위한 KafkaConfig 추가
- TopicBuilder를 통한 자동 토픽 생성 기능 구현
- 환경별 Kafka 설정 (dev/prod/test) application.yml에 추가
- Alert 처리용 Kafka 이벤트 DTO 생성 (AlertCreatedEvent, UserAlertEvent)
- 중복 처리 방지를 위한 AlertStatusRepository 메서드 추가
feat: Alert Kafka Producer/Consumer 서비스 구현
- AlertKafkaProducer: Alert 생성 이벤트 및 사용자별 알림 이벤트 발행
- AlertKafkaConsumer: 2단계 비동기 처리 (Alert 생성 → 사용자 필터링 → 개별 알림)
- 사용자 ID 기반 파티셔닝으로 메시지 순서 보장
- 수동 커밋을 통한 메시지 처리 신뢰성 확보
- 멱등성 보장을 위한 중복 처리 방지 로직 추가
feat: Alert 서비스에 Kafka 비동기 처리 통합
- AlertService에 비동기 Alert 생성 메서드 추가
- AlertController에서 비동기 처리 엔드포인트 연동
- 기존 동기 방식 유지하면서 비동기 옵션 제공
- Alert 생성 후 즉시 응답 반환으로 응답시간 개선
feat: Alert Kafka 성능 테스트 및 운영 도구 추가
- 동기 vs 비동기 성능 비교 테스트 (BasicPerformanceTest)
- 대용량 부하 테스트 (AlertLoadTest, …
> feat: Kafka 활용 비동기 처리

- src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaConsumer.java
- src/main/java/kr/ssok/ssom/backend/global/config/KafkaConfig.java
#165 
fix : kafka consumer 역직렬화 문제
> fix : kafka consumer 역직렬화 문제

- src/main/java/kr/ssok/ssom/backend/domain/logging/service/Impl/LoggingServiceImpl.java
#172 
fix : 로그 SSE Security Context 충돌 문제 해결
Alert SSE 와 동일하게 적용하여 문제 해결
> fix : 로그 SSE Security Context 충돌 문제 해결

- src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaConsumer.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/kafka/AlertKafkaProducer.java
#165 
- AlertKafkaConsumer에 최대 재시도 제한 (3회) 추가
- 재시도 초과 시 DLQ(Dead Letter Queue) 전송 로직 구현
- 무한 재시도 방지를 위한 오프셋 커밋 로직 추가
- AlertKafkaProducer에 DLQ 전송 메서드 구현
> feat: Kafka Consumer 실패 처리 메커니즘 개선

- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/controller/AlertPerformanceTestController.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertDevopsRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/dto/AlertGrafanaRequestDto.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertRepository.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/repository/AlertStatusRepository.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertPerformanceTestService.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertPerformanceTestServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/alert/service/AlertServiceImpl.java
- src/main/java/kr/ssok/ssom/backend/domain/user/security/config/SecurityConfig.java
#186 
test : 오픈서치 알림 webhook 비동기, 동기 비교 테스트를 위한 푸시알림 부분 주석처리
/api/alert/opensearch -> 비동기 방식
/api/alert/opensearch/sycn -> 동기 방식
> test : 오픈서치 알림 webhook 비동기, 동기 비교 테스트를 위한 푸시알림 부분 주석처리
